services:
  # social-backend:
  #   build: .
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #   depends_on:
  #     - mysqlhost
  #   networks:
  #     - SocialNetwork

  mysqlhost:
    image: mysql:8.0.45
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - SocialNetwork
    env_file:
      - .env.prod

volumes:
  mysql-data:
networks:
  SocialNetwork:
    driver: bridge
