services:
  # social-backend:
  #   build: .
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - Kafka__BootstrapServers=kafka:9092
  #   depends_on:
  #     - mysqlhost
  #     - redis
  #     - kafka
  #   networks:
  #     - SocialNetwork

  mysqlhost:
    image: mysql:8.0.45
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - SocialNetwork
    env_file:
      - .env.prod
  redis:
    image: redis:7.0.11
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - SocialNetwork
  kafka:
    image: apache/kafka:3.9.0
    container_name: socialtech-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - SocialNetwork
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESSKEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRETKEY}
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  mysql-data:
networks:
  SocialNetwork:
    driver: bridge
